香港频道,#genre#  
翡翠台,id=jade_twn  
翡翠台备份,id=Jade_xue  
iNews 新闻台,id=inews_twn  
J 2,id=j2_twn  
珍珠台,id=pearl_twn  
凤凰香港,id=hkphoenix_twn  
HOY资讯台,id=hoycaijing_twn  
RHK 31,id=rhk31_twn  
viutv,id=viu1_twn  
RHK 32,id=rhk32_twn  
凤凰资讯,id=phoenixinfo_hd  
viutv6,id=viusix_twn  

中央视频道,#类型#  
CCTV-1综合频道高清,id=cctv1  
CCTV-2财经频道,id=cctv2  
CCTV-3综艺频道,id=cctv3  
CCTV-4 中文国际,id=cctv4  
CCTV-4新闻频道,id=Cctv4  
CCTV-5 体育频道,id=cctv5  
CCTV-5+体育赛事高清,id=cctv5plus  
CCTV-6 电影频道,id=cctv6  
CCTV-7军事农业频道,id=cctv7  
CCTV-8电视剧高清,id=cctv8hd  
CCTV-9记录频道HD,id=cctv9hd  
CCTV-10科教频道高清,id=cctv10hd  
CCTV-11戏曲频道,id=cctv11  
CCTV-12社会与法,id=cctv12  
CCTV-13新闻频道,id=cctv13  
CCTV-14 少儿频道,id=cctv14  
CCTV-15频道音乐,id=cctv15  

体育频道,#genre#  
Astro 超级联赛 1,id=go_assp1  
Astro EPL 1 备份，id=go_assp1x  
Astro 超级联赛 2,id=go_assp2  
Astro 看台,id=go_assp3  
Astro Football,id=go_assp4  
Astro Sports Plus，id=go_sportsplus  
天文羽毛球1,id=go_badminton1  
Astro 羽毛球 2,id=go_badminton2  
Astro W-体育，id=go_assp5  
超级运动 1,id=Assp1  
超级运动2，id=Assp2  
超级跑车 3,id=Assp3  
超级跑车 4,id=Assp4  
WWE,id=Wwe  
搏击运动,id=Fs  
NBA电视台，id=Nba  
Astro Cricket，id=Acricket  
Astro Golf,id=Agolf  
Tnt体育1,id=6fac0aaead  
TNT体育2，id=d9a76a79cc  
TNT体育3，id=5fea4d73db  
TNT体育4，id=tntsport4  
索尼 Ten 1，id=ten1_raj  
索尼 Ten 2，id=ten2_raj  
索尼 Ten 3，id=ten3_raj  
SPOTV 1 高清,id=go_spotv  
SPO电视2,id=go_spotv2  
Skysports F1,id=tiankongf1  
Skysports Cricket，id=tiankongcricket  
Skysports EPL,id=tiankongepl  
Skysports 主赛事,id=tiankongmain  
天空体育新闻，id=tiankongnews  
Skysports Mix，id=tiankongmix  
CCTV-5 体育频道,id=cctv5  
CCTV-5+体育赛事高清,id=cctv5plus  
爱尔达体育2台,id=eltasport2_twn  
爱尔达体育3台,id=eltasport3_twn  
橄榄球通行证电视，id=Rugbypasstv  
RTM 体育高清,id=Rtmsport  
竞技场，id=竞技场  
竞技场 2,id=Arena2  
博拉竞技场 1,id=Bolaarena1  
博拉竞技场 2,id=Bolaarena2  
Astro Beinsports 1,id=Astrobein1  
Astro Beinsports 2,id=Astrobein2  
Astro Beinsports 3,id=Astrobein3  

台湾频道,#genre#  
TVBS新闻台,id=tvbs_n  
TVBS欢乐台（备份）,id=tvbshuanle_twn  
TVBS高清,id=tvbs  
中天新闻 HD,id=ctinews  
中天娱乐 CTI Entertainment,id=ctient  
中天综合CTI Metro,id=ctizhonghe  
中天亚洲台,id=ctiasia_twn  
台视 TTV HD,id=ttv_taiwan  
台视新闻台,id=ttvnews_twn  
台视综合台,id=ttvzhonghe  
中视高清,id=zhongshihd_twn  
中视新闻台,id=zhongshinews_twn  
民视HD,id=ftvhd_taiwan  
民视新闻台 民视新闻,id=ftvnew_taiwan  
民视台湾台,id=ftvtaiwan_twn  
华视 CTS HD,id=ctshd_twn  
公视 CTV,id=ctv18_twn  
八大第一GTV First,id=badafirst  
八大综合GTV Metro,id=badazhonghe  
八大戏剧GTV Drama,id=baddrama  
八大娱乐 GTV Entertainment,id=badaentertain  
HBO_HD,id=hbohd_twn  
好莱坞电影，id=hollywoodmovies_twn  
三立台湾 Sanli Taiwan,id=sanlitaiwan  
三立戏剧台,id=sanlixiju_twn  
三立综合三立地铁,id=sanlizhonghe  
三立都会台,id=sanlidouhui  
东森新闻 东森新闻,id=ettvnews  
CINEMAX,id=cinemax_twn  
东森综合 ETTV Metro,id=ettvzhonghe  
东森戏剧 东森戏剧,id=ettvdrama  
东森超视,id=ettvsuper  
东森财经新闻 东森财经,id=ettvcaijing_twn  
寰宇财经,id=huanyutaiwan_twn  
寰宇新闻台,id=huayuxinwen_twn  
公视2,id=ctv2_twn  
大爱1台,id=daai_twn  
非凡新闻台,id=feifannews_twn  
龙华戏剧 龙华戏剧,id=lunghuaxiju_twn  
龙华经典台,id=lunghuajingdian_twn  
龙华偶像,id=lunghuaidol_twn  
AXN台湾,id=axn_twn  
靖天国际台,id=jingtianintl_twn  
年代新闻,id=niandainews_twn  
纬来日本台,id=videolandjapan  
纬来电影台,id=videolandmovie  
纬来体育台,id=videolandsport  
纬来综合台,id=videolandzonghe  
纬来育乐,id=videolandyule  
纬来精彩,id=videolandspecial_twn  
好消息2,id=good2_twn  
大爱2台,id=daai2_twn  
亚洲美食,id=afc_twn  
美食星球,id=foodplanet_twn  
旅游亚洲 TLC Asia,id=tlc_twn  
东森电影 东森电影,id=ettvmovie  
阿里郎 Arirang,id=arirang_twn  
博斯运动1,id=bosisport1_twn  
博斯运动2,id=bosisport2_twn  
博斯高球2 HD,id=bosigolf2_twn  
博斯网球 HD,id=bositennis_twn  
东森洋片 ETTV Western,id=ettvwestern  
龙华洋片 龙华西游,id=lunghuawestern_twn  
博斯无限,id=bosiunlimited_twn  
MTV 直播,id=mtvhd_twn  
龙详时代,id=lungxiangtime_twn  
EYETV旅游,id=eyetvtravel_twn  
靖天卡通台,id=jingtiancartoon_twn  
EYETV 戏剧,id=eyetvxiju_twn  
卫视中文台明星电影中文,id=weishichinese_twn  
东森幼幼 Yoyo TV,id=yoyo_twn  
卫视电影台,id=weishimovie_twn  
美亚电影,id=meiyamovie_twn  
爱尔达影剧台,id=eltayingju_twn  
爱尔达综合台,id=eltazonghe_twn  
星卫电影,id=xingwei_movie  
AFC亚洲旅游台,id=asiatravel_twn  
爱尔达影剧,id=eltayingju_twn  
爱尔达体育2台,id=eltasport2_twn  
爱尔达体育3台,id=eltasport3_twn  

电影频道,#类型#  
HBO_HD,id=hbohd_twn  
HBO_HITS,id=hbohit_twn  
好莱坞电影，id=hollywoodmovies_twn  
CCTV-6,id=cctv6  
CINEMAX,id=cinemax_twn  
Cinemax,id=Cinemax  
AXN台湾,id=axn_twn  
大爱2台,id=daai2_twn  
东森电影 东森电影,id=ettvmovie  
东森洋片 ETTV Western,id=ettvwestern  
龙华洋片 龙华西游,id=lunghuawestern_twn  
Animax,id=Animax  
龙详时代,id=lungxiangtime_twn  
电影现在高清，id=moviesnow_raj  
明星电影高清，id=starmovies_raj  
卫视中文台明星电影中文,id=weishichinese_twn  
HBO 家庭,id=Hbofamily  
Hits,id=Hits  
华纳电视，id=WarnerTV  
卫视电影台,id=weishimovie_twn  
HBO HD,id=Hbo  
美亚电影,id=meiyamovie_twn  
HBO签名，id=Hbosignature  
HBO Hits，id=Hbohitshd  
星卫电影,id=xingwei_movie  
SCM,id=Weishimovie  
梦工厂，id=梦工厂  
刺激，id=刺激  
热门电影，id=Hitsmovie  
一,id=一  
tvN电影，id=Tvnmovie  
天界经典,id=Celestial2  
天映电影高清,id=Celestialindo  
Axn HD,id=Axn  
派拉蒙网络，id=Paramountnetwork  
Astrol Kplus,id=Kplus  
摇滚行动，id=Rockaction  
摇滚娱乐，id=Rockentertain  

纪录频道,#流派#  
Natgeo_HD,id=natgeohd_twn  
NatGeo_Wild HD,id=natgeowild_twn  
动物星球，id=animalplanet_twn  
探索亚洲,id=discoverytwn_twn  
CI，id=ci_twn  
亚洲旅行，id=asiatravel_twn  
探索高清，id=discoveryhd_twn  
亚洲美食,id=afc_twn  
美食星球,id=foodplanet_twn  
旅游亚洲 TLC Asia,id=tlc_twn  
NatGeo HD,id=Natgeo  
时尚电视，id=fashiontv_twn  
历史，id=历史  
BBC地球高清，id=bbcearth_twn  
BBC 地球生活方式，id=bbclifestyle_twn  
MTV 直播,id=mtvhd_twn  
NatGeo Wild HD，id=Natgeowild  
动物星球（英语），id=AnimalPlanet  
TLC，id=Tlc  
Foodnetwork Hd，id=Foodnetwork  
HGTV,id=HGTV  
AFC亚洲旅游台,id=asiatravel_twn  

新闻频道,#genre#  
天空新闻，id=skynews_twn  
ABC新闻，id=abcnews_glo  
东森财经新闻 东森财经,id=ettvcaijing_twn  
CBS HD,id=cbshd_glo  
CBSN HD,id=cbsn_glo  
法国24电视台，id=france24_twn  
DW（德语），id=dw_twn  
NHK世界,id=nhkworld_japan  
福克斯新闻，id=foxnews_twn  
CGTN,id=CGTN  
CNN国际，id=Cnn  
CNN备份，id=cnn_twn  
CNBC，id=cnbc_twn  
CNA,id=cna  
BBC世界新闻，id=bbcnews_twn  
BBC世界新闻，id=Bbcnews  
彭博新闻社，id=bloomberg_twn  
半岛电视台，id=aljazeera_twn  

儿童频道,#类型#  
婴儿电视 Eng,id=Babytv  
CBeebies,id=Cbeebies  
儿童电视，id=KidsTV  
陌陌电视,id=momo1_twn  
Animax,id=Animax  
MiaoMi,id=MiaoMi  
靖天卡通台,id=jingtiancartoon_twn  
东森幼幼 Yoyo TV,id=yoyo_twn  
卡通网络，id=Cn  
尼克国际儿童频道，id=Nickelodeon  
Nick Jr，id=Nickjr  

新加坡频道,#genre#  
5频道，id=Channel5HD  
8频道，id=Channel8HD  
Suria,id=Suria  
频道U，id=ChannelU  
瓦桑瑟姆，id=Vasantham  
CNA备份,id=cna_twn  
MeWatch 第 5 章,id=Mewatch_ch5  
MeWatch 第 8 频道,id=Mewatch_ch8  
MeWatch Ch U,id=Mewatch_chU  
MeWatch Suria,id=Mewatch_Suria  
MeWatch Vasantham，id=Mewatch_Vasantham  
MeWatch CNA,id=Mewatch_cna  

马来西亚频道,#genre#  
TV1,id=TV1  
TV1备份,id=TV1_backup  
TV2,id=TV2  
TV3,id=TV3  
TV3 SD,id=TV3_mega  
NTV7,id=NTV7  
TV8,id=TV8  
TV9,id=TV9  
Ria，id=Ria-0  
Ria-3，id=Ria_backup  
Al-Hijrah，id=Alhijrah  
Al-Hijrah 备份，id=Alhijrah_backup  
Awani,id=Awani  
马新社,id=Bernama  
Prima,id=Prima-0  
Prima 备份,id=AAprima1  
Prima 备份 2,id=AAprima  
Ceria,id=Ceria  
Astro MTV,id=AstroMTV  
麦加直播高清,id=quran_mido  
麦地那 HD,id=sunnah_mido  
绿洲，id=绿洲  
Siar，id=Siar  
Citra,id=AAcitra  
Citra 备份,id=AAcitra1  
Sensasi,id=Sensasi  
光环，id=光环  
Rania,id=Rania  
KBS世界,id=KBS  
嘘，id=嘘  
很棒的电视，id=Dsangat  
Astro Sonypix,id=Asonypix  
索尼高清,id=SetOne  
电视N，id=电视N  
AEC,id=AEC  
华丽台 HD （华丽台）,id=Wlt  
欢喜台 HD （Hua Hee Tai）,id=Huahee  
Astro QJ,id=Quanjia  
TVB翡翠台,id=Tvbjade  
TVB亚洲,id=Tvbasia  
TVB娱乐，id=Tvbentertainment  
TVB经典,id=Tvbclassic  
AOD,id=Aodhd  
一,id=一  
TVB 星河台 Xing He,id=Xinhe  
爱奇艺 iQiyi,id=Qiyi  
动物星球（英语），id=AnimalPlanet  
tvN电影，id=Tvnmovie  
CNN备份，id=cnn_twn  
天界经典,id=Celestial2  
CNBC，id=cnbc_twn  
TLC，id=Tlc  
CNA,id=cna  
BBC世界新闻，id=bbcnews_twn  
Foodnetwork Hd，id=Foodnetwork  
HGTV,id=HGTV  
Goshop，id=Goshop  
天映电影高清,id=Celestial  
Axn HD,id=Axn  
派拉蒙网络，id=Paramountnetwork  
Astrol Kplus,id=Kplus  
AFC亚洲旅游台,id=asiatravel_twn  
摇滚行动，id=Rockaction  
彭博新闻社，id=bloomberg_twn  
半岛电视台，id=aljazeera_twn  
摇滚娱乐，id=Rockentertain  
RTM 体育高清,id=Rtmsport  
竞技场，id=竞技场  
竞技场 2,id=Arena2  
博拉竞技场 1,id=Bolaarena1  
博拉竞技场 2,id=Bolaarena2  
Astro LOL,id=Astro_lol  
Astro Rusi,id=Rusi  
WION，id=Wion  
RTM 东盟,id=Rtmasean  
HBO HD,id=Hbo  
HBO签名，id=Hbosignature  
HBO Hits，id=Hbohitshd  
NatGeo Wild HD，id=Natgeowild  
卡通网络，id=Cn  
尼克国际儿童频道，id=Nickelodeon  
Nick Jr，id=Nickjr  
梦工厂，id=梦工厂  

印尼频道,#genre#  
TVRI National,id=TVRI  
RCTI，id=Rcti  
Kompass TV,id=Kompass  
星期六新闻,id=BeritaSatu_eko  
Indosiar HD,id=Indosiar  
AnTV,id=Antv  
MNC电视台，id=Mnctv  
交易 7,id=Trans7_eko  
Transtv,id=Transtv  
JTV,id=JTV_eko  
地铁电视台，id=metrotv_eko  
Cinemax,id=Cinemax  
SCTV,id=SCTV  
Tvone，id=Tvone  
TVMU,id=TVMU_eko  
GTV，id=Gtv  
RTV，id=Rtv  
Jak TV,id=JakTV  
iNews TV，id=Inewstv  
大爱TV,id=DaaiTV  
网络电视,id=NetTV  
EWTN,id=Ewtn  
Tawaf 电视台,id=TawafTV  
Vision Prime,id=VisionPrime  
穆斯林电视台，id=MuslimTV  
音乐电视，id=MusicTV  
生活方式和时尚,id=Lifestyle  
Hits,id=Hits  
华纳电视，id=WarnerTV  
SCM,id=Weishimovie  
刺激，id=刺激  
搏击运动,id=Fs  
热门电影，id=Hitsmovie  
一,id=一  
tvN电影，id=Tvnmovie  
天映电影高清,id=Celestialindo  
摇滚行动，id=Rockaction  
摇滚娱乐，id=Rockentertain  

印度频道,#genre#  
阳光电视高清,id=Suntv  
Star Vijay，id=Starvijay  
颜色泰米尔语，id=Colorstam  
太阳音乐,id=Sunmusic  
Astro Sunlife,id=Sunlife  
Astro Vaanavil，id=Vaanavil  
Zee Tamil，id=Zeetamil  
Zee Business,id=Zeebusiness  
新闻 18 泰米尔语，id=news18tamil_raj  
Adithya,id=Adithya  
Makkal TV，id=Makkaltv  
Zee Action,id=Zeeaction  
Astro KTV,id=Astroktv  
Zee TV HD，id=Zeetvhd  
Zee Cinema HD，id=Zeecinemahd  
彩色高清,id=Colorhd  
Starplus HD,id=Starplushd  
图片高清,id=Npicture  
Zee 新闻，id=Zeenews  
Asianet,id=asianet_raj  
亚洲网新闻,id=asianetnews_raj  
探索世界泰米尔语，id=discoveryworldtam_raj  
历史泰米尔语，id=historytam_raj  
NatGeo 泰米尔语，id=natgeotamil_raj  
Natgeo Wild Tamil，id=natgeowildtamil_raj  
Discovery Kids Tamil，id=discoverykidtamil_raj  
索尼耶泰米尔语，id=sonyyaytam_raj  
印度太阳电视台，id=suntv_raj  
Starmaa HD,id=starmaa_raj  
Starmaa 电影高清，id=starmamovies_raj  
Bollyone,id=Bollyone  
Vijay Super，id=vijaysuper_raj  
Vellithirai,id=Vellithirai  
Astro Sonypix,id=Asonypix  
Astro Sunmusic，id=Sunmusic  

泰国频道,#genre#  
泰国3频道，id=ch3_pat  
泰国第五频道，id=ch5_pat  
泰国7频道，id=ch7_pat  
MCOT HD 泰国-1,id=mcot_pat  
PPTV泰国1,id=pptv_pat  
泰国 泰国,id=thaithai_pat  
阿玛林，id=amarin_pat  
通道 8,id=ch8_pat  
GmmOne，id=gmmone_pat  
Mono，id=mono_pat  
Thairath，id=thairath_pat  
tpbs,id=tpbs_pat  
工作点,id=workpoint_pat  
Gmm频道,id=gmmchannel_pat  
国家，id=nation_pat  
Tnn24,id=tnn24_pat  
Nbt，id=nbt_pat  
新的，id=new_pat  
TPTV,id=tptv_pat  

英国频道,#genre#  
BBC 1，id=bbc1_antik  
BBC 2，id=bbc2_antik  
CBBC,id=cbbc_antik  
More4,id=more4_antik  
自由体育，id=freesports_antik  
天空新闻，id=skynews_twn  
选择电视，id=picktv_antik  
itv 1,id=itv1_antik  
itv 2,id=itv2_antik  
欧洲新闻，id=euronews_antik  
第四频道，id=channel4_antik  
NatGeo HD,id=Natgeo  
CBeebies,id=Cbeebies  
历史，id=历史  
儿童电视，id=KidsTV  
法国24电视台，id=france24_twn  
DW（德语），id=dw_twn  
BBC地球高清，id=bbcearth_twn  
BBC 地球生活方式，id=bbclifestyle_twn  
MTV 直播,id=mtvhd_twn  
明星电影高清，id=starmovies_raj  
NHK世界,id=nhkworld_japan  
华纳电视，id=WarnerTV  
HBO HD,id=Hbo  
NatGeo Wild HD，id=Natgeowild  
尼克国际儿童频道，id=Nickelodeon  
Nick Jr，id=Nickjr  
刺激，id=刺激  
CGNTV,id=CGTN  
热门电影，id=Hitsmovie  
动物星球（英语），id=AnimalPlanet  
CNBC，id=cnbc_twn  
TLC，id=Tlc  
BBC 世界新闻，id=bbcworldnews_antik  
HGTV,id=HGTV  
Axn HD,id=Axn  
Skysports F1,id=tiankongf1  
Skysports Cricket，id=tiankongcricket  
彭博新闻社，id=bloomberg_twn  
Skysports EPL,id=tiankongepl  
Skysports 主赛事,id=tiankongmain  
天空体育新闻，id=tiankongnews  
半岛电视台，id=aljazeera_twn  



